---
title: "Eyes, Empathy and Action"
author: "Katharina Hellmund & Nadia Hajighassem"
date: "2023-12-09"
output: html_document
---

# Setup and Preparation

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include = TRUE, message = FALSE, warning = FALSE)

#Calling functions
source("Functions.R")

#Calling packages
pacman::p_load(
  "XML",
  "tidyverse",
  "fs",
  "assertthat",
  "stringi",
  "dtw",
  "RTransferEntropy",
  "signal",
  "conflicted",
  "Rcpp",
  "future",
  "ggplot2",
  "hrbrthemes"
)

#Aesthetic setup
theme_set(theme_ipsum())
bar_colour <- "#0e3b85"
```

# Pre-processing

## Loading in Data and Cleaning

```{r load_personality_data}
#No 9 or 11 :) the data jumps.
#Unknown data could be: A13, A1, A6
personality_questionnaire <- read_csv('data/PercAct23_Mocap_personality_questionnaires.csv')%>% 
  dplyr::filter(`I was a participant in the Mocap workshop`=="Yep") %>%
  mutate(`Participant ID` = case_when(
    `Participant ID` == "7A" ~ "A7",
    `Participant ID` == "b12" ~ "B12",
    `Participant ID` == "6b" ~ "B6",
    `Participant ID` == "12 A" ~ "A12",
    `Participant ID` == "B01" ~ "B1",
    `Participant ID` == "A" ~ "?A?",
    `Participant ID` == "nnn" ~ "?n?",
    `Participant ID` == "H7" ~ "?h7?",
    TRUE ~ `Participant ID`  # If no match, keep the original value
  )) %>% 
    dplyr::filter(!grepl("\\?", `Participant ID`))   # Exclude rows with "?" in Participant DELETE AFTER IDENTIFY MISSING DATA



```

```{r load_subjective_data}
subjective_questionnaire_A <- read_csv('data/PerAct23_Mocap_subjective_questionnaires.csv') %>% 
  select(
    -"Participant B ID", 
    -ends_with("B_LeadFollow"), 
    -ends_with("B_FollowLead"), 
    -ends_with("B_JointLead"), 
    -ends_with("Custom"), 
    -"Describe the custom condition", 
    -"Tidsstempel") %>% 
  rename_all(
    ~gsub("A_", "", .)) %>% 
  rename(
    "Participant ID" = "Participant A ID")

  

subjective_questionnaire_B <- read_csv('data/PerAct23_Mocap_subjective_questionnaires.csv') %>% 
  select(
    -"Participant A ID", 
    -ends_with("A_LeadFollow"), 
    -ends_with("A_FollowLead"), 
    -ends_with("A_JointLead"), 
    -ends_with("Custom"), 
    -"Describe the custom condition", 
    -"Tidsstempel")%>% 
  rename_all(
    ~gsub("B_", "", .)) %>% 
  rename(
    "Participant ID" = "Participant B ID")

  
subjective_questionnaire <- bind_rows(subjective_questionnaire_A,subjective_questionnaire_B)

# #Making seperate dataframes for different conditions???
# subjective_questionnaire_Leader <- subjective_questionnaire %>% 
#   select(
#     -ends_with("Follower"),
#     -ends_with("JointLead"))
# 
# subjective_questionnaire_Follower <- subjective_questionnaire %>% 
#     select(
#     -ends_with("Leader"),
#     -ends_with("JointLead"))
# subjective_questionnaire_JointLead <- subjective_questionnaire %>% 
#     select(
#     -ends_with("Leader"),
#     -ends_with("Follower"))

survey_data <- merge(subjective_questionnaire, personality_questionnaire, by = "Participant ID")
```

```{r eye_data}

```

```{r motion_data}

```

```{r final_data_merging}

```

# Exploratory data-analysis

```{r}
#Gender plot
survey_data %>% 
  ggplot(aes(x=Gender))+
  geom_bar(fill= bar_colour)+
  labs(title = "Distribution of Gender",
       x = "Gender",
       y = "Count")
  

#Age plot
survey_data %>% 
  ggplot(aes(x=Age))+
  geom_bar(fill = bar_colour)+
  labs(title = "Distribution of Age",
       x = "Age",
       y = "Count")
```
